blog_project/urls.py
from django.conf import settings # new
from django.conf.urls.static import static # new
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('universe-admin/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),

    # Local apps
    path('', include('pages.urls')),
    path('blog/', include('blogs.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/urls.py
from django.urls import path
from .views import BlogListView, BloggerListView, BlogDetailView, BloggerDetailView, \
    BlogCommentCreate

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('bloggers/', BloggerListView.as_view(), name='blogger_list'),
    path('<uuid:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blogger/<uuid:pk>', BloggerDetailView.as_view(), name='author_detail'),
    path('blog/<uuid:pk>/comment/', BlogCommentCreate.as_view(), name='blog_comment'),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

users/urls.py
from django.urls import path

from .views import SignupPageView

urlpatterns = [
    path('signup/', SignupPageView.as_view(), name='signup'),
]

blogs/models.py
import uuid # new
from django.contrib.auth import get_user_model # new
from django.db import models
from django.urls import reverse # new

class Blog(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    content = models.TextField(max_length=75000)
    published = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        verbose_name_plural = 'Blogs'
        verbose_name = 'Blog'
        ordering = ['-published']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog_detail', args=[str(self.id)])


class Author(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('author_detail', args=[str(self.id)])


class BlogComment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    description = models.TextField(max_length=1000,
                               help_text='Leave a comment in language (e.g. English, French, Japanese, Russian, Ukrainian etc.)')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
    post_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['post_date']

    def __str__(self):
        len_title=75
        if len(self.comment)>len_title:
            titlestring=self.comment[:len_title] + '...'
        else:
            titlestring=self.comment
        return titlestring

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# get_user_model - ссылается на model CustomUser
class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

blogs/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse

from .models import Blog, Author, BlogComment
from django.contrib.auth import get_user_model

from django.shortcuts import get_object_or_404

class BlogListView(ListView):
    paginate_by = 5
    model = Blog
    context_object_name = 'blog_list'
    template_name = 'blogs/blog_list.html'


class BloggerListView(ListView):
    model = Author
    context_object_name = 'blogger_list'
    template_name = 'blogs/blogger_list.html'


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blogs/blog_detail.html'


class BloggerDetailView(DetailView):
    model = Author
    template_name = 'blogs/blogger_detail.html'


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    model = BlogComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.blog = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog_detail', kwargs={'pk': self.kwargs['pk']})

pages/views.py
from django.views.generic import TemplateView

from blogs.models import Blog

class HomePageView(TemplateView):
    template_name = 'home.html'

users/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm


class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Blogs{% endblock title %}</title>
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
{#  <nav class="">#}
{#    <a href="{% url 'account_signup' %}">Sign Up</a>#}
{#  </nav>#}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          <ul class="sidebar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'blog_list' %}">All blogs</a></li>
            <li><a href="{% url 'blogger_list' %}">All bloggers</a></li>
{#            <li style="margin-top: 25px"><a href="{% url 'account_login' %}">Login</a></li>#}
{#            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>#}
            {% if user.is_authenticated %}
              <li class="mt-2"><a href="{% url 'account_logout' %}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'account_login' %}">Log In</a></li>
              <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10 mt-3">
        {% block content %}{% endblock %}
          {% if is_paginated %}
            <div class="pagination mt-4">
              <span class="step-links">
                  {% if page_obj.has_previous %}
                      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}

                  <span class="current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>

                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
            </div>
          {% endif %}
      </div>
    </div>
  </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/blogs/blog_detail.html
{% extends '_base.html' %}

{% block title %}{{ blog.title }}{% endblock title %}

{% block content %}
  <h1>{{ blog.title }}</h1>
  <p><strong>Post date</strong> {{ blog.published }}</p>
  <p><strong>Author:</strong> {{ blog.author }}</p>
  <div><strong>Description:</strong><p>{{ blog.content }}</p></div>

  <h1>Comments</h1>
  
  {% for comment in blog.blogcomment_set.all %}
    <hr>
    <p>{{ comment.author }} ({{ comment.post_date }}) - {{ comment.description }}</p> 
  {% endfor %}
    <hr>
  {% if user.is_authenticated %}
    <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a>
  {% else %}
    <p><a href="{% url 'account_login' %}">Login</a> to add a new comment</p>
  {% endif %}
{% endblock %}

templates/blogs/blog_list.html
{% extends '_base.html' %}

{% block title %}Blogs{% endblock %}

{% block content %}
  <h1>All blogs</h1>
  {% for blog in blog_list %}
    <li class="ml-4"><a href="{{ blog.get_absolute_url }}">{{ blog.title }} ({{ blog.published }}) - {{ blog.author }}</a></li>
  {% endfor %}
{% endblock %}

templates/blogs/blogcomment_form.html
{% extends '_base.html' %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog_detail' blog.pk %}">{{ blog.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="btn btn-primary" type="submit" value="Submit" />

</form>

{% endblock %}

templates/blogs/blogger_detail.html
{% extends '_base.html' %}

{% block title %}{{ author.last_name }} {{ author.first_name }}{% endblock title %}

{% block content %}
  <h1><strong>Blogger</strong>: {{ author.last_name }} {{ author.first_name }}</h1>
  <h5>Date of birth: {{ author.date_of_birth }}</h5>
  <h5>Date of death: {{ author.date_of_death }}</h5>
  <div>
    <h5>Blogs list</h5>
    {% for blog in author.blog_set.all %}
      <li class="ml-4"><a href="{{ blog.get_absolute_url }}">{{ blog.title }} ({{ blog.published }})</a></li>
    {% endfor %}
  </div>
{% endblock %}

templates/blogs/blogger_list.html
{% extends '_base.html' %}

{% block title %}Bloggers{% endblock %}

{% block content %}
  <h1>All bloggers</h1>
  {% for blogger in blogger_list %}
    <li class="ml-4"><a href="{{ blogger.get_absolute_url }}">{{ blogger.last_name }} {{ blogger.first_name }}</a></li>
  {% endfor %}
{% endblock %}

templates/home.html
{% extends '_base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
  <h1>Homepage</h1>
  {% if user.is_authenticated %}
    Hi {{ user.email }}!
    <p class="mt-2"><a href="{% url 'account_logout' %}">Log Out</a></p>
  {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'account_login' %}">Log In</a>
    <a href="{% url 'account_signup' %}">Sign Up</a>
  {% endif %}
{% endblock content %}